..
.
.
.TH multiraw 7 "29 March 2013" "multiraw version 1.0"
.
.
.
.SH NAME
.
.B multiraw
.
.SH SYNOPSIS
.

multiraw -e '-e -R' -v -t -a /path/to/file

multiraw -e '-6 -T -o 1' -v -t -a /path/to/file

multiraw -e '-T -o 1' -v -t -a /path/to/file

.
.SH DESCRIPTION

Processing Camera Raw files to JPEG, TIFF, or PPM formats is extremely time intensive. Utilizing multiple threads on multi-core systems can realize an increase of productivity and time savings of 60%.

The multiraw.c program allows the user to batch convert Camera Raw format files in parallel using pthreads. The user may specify the number of threads to run, or they may use the Auto Thread switch which will cause the software to determine the appropriate number of threads based on the task requested. By default, multiraw.c calls dcraw-m, which is included. If the user wishes to use the unmodified dcraw program, it may be specified using the -o switch.

multiraw uses dcraw-m, a modified version of dcraw which automatically rotates exported thumbnails and has a camera timezone offset adjustment variable.

Ref:

https://dx.burplex.com/bin/autorot.html

https://dx.burplex.com/bin/photohack.html

https://dx.burplex.com/bin/multiraw.html

.
.SH OPTIONS
.IP -u
Display installed ports with update status only.
.IP -e
Command Line Options to pass to dcraw-m, example: -e '-e -R'
.IP -n
Number of Threads
.IP -a
Automatically determine number of threads
.IP -t
Report Exec Time (secs)
.IP -v
Verbose Messages
.IP -o
Use original dcraw (dcraw-m is default)
.IP -h
Help

.SH FILES
multiraw.c requires the path to a file containing Raw images to process. This file may be created using the Image previewer Qt4 Application in the FreeBSD ports system under graphics/burplex. The file shall have one filename per line.
.
.
.SH AUTHOR
.
Manual page by Waitman Gobble
